# Generated by Django 4.2.16 on 2026-08-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('patente', models.CharField(max_length=15, unique=True)),
                ('marca_modelo', models.CharField(max_length=100)),
                ('tipo_vehiculo', models.CharField(max_length=50)),
                ('capacidad_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacidad_m3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('En Viaje', 'En Viaje'), ('En Mantenimiento', 'En Mantenimiento'), ('Fuera de Servicio', 'Fuera de Servicio')], default='Disponible', max_length=30)),
                ('kilometraje', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
            },
        ),
    ]
